Script started on Mon 28 Nov 2016 08:56:34 PM EST
pavithra@topcat:~/cs630/hw4$ sqlplus pavithra/pavithra@//dbs3.cs.umb.edu/dbs3 @dropairdb.sql

SQL*Plus: Release 12.1.0.2.0 Production on Mon Nov 28 20:56:40 2016

Copyright (c) 1982, 2014, Oracle.  All rights reserved.

Last Successful login time: Mon Nov 28 2016 20:55:25 -05:00

Connected to:
Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
With the Partitioning, OLAP, Advanced Analytics and Real Application Testing options


Table dropped.


Table dropped.


Table dropped.


Table dropped.


Table dropped.


Table dropped.


Table dropped.


Table dropped.

Disconnected from Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
With the Partitioning, OLAP, Advanced Analytics and Real Application Testing options
pavithra@topcat:~/cs630/hw4$ sqlplus pavithra/pavithra@//dbs3.cs.umb.edu/dbs3 @createairdb.sql

SQL*Plus: Release 12.1.0.2.0 Production on Mon Nov 28 20:56:49 2016

Copyright (c) 1982, 2014, Oracle.  All rights reserved.

Last Successful login time: Mon Nov 28 2016 20:56:06 -05:00

Connected to:
Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
With the Partitioning, OLAP, Advanced Analytics and Real Application Testing options


Table created.


Table created.


Table created.


Table created.


Table created.


Table created.


Table created.


Table created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


1 row created.


Commit complete.

Disconnected from Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
With the Partitioning, OLAP, Advanced Analytics and Real Application Testing options
pavithra@topcat:~/cs630/hw4$ javac -cp ojdbc6.jar:. AssignFlights1.java
Picked up _JAVA_OPTIONS: -Djava.security.egd=file:/dev/../dev/urandom
pavithra@topcat:~/cs630/hw4$ java -cp ojdbc6.jar:. AssignFlights1
Picked up _JAVA_OPTIONS: -Djava.security.egd=file:/dev/../dev/urandom
Please enter information for connection to the database
Using Oracle (o) or MySql (m)? (defaults to Oracle)o
Oracle username: pavithra
Oracle password: pavithra
use canned Oracle connection string (y/n): y
host: (Defaults to dbs3.cs.umb.edu) 
port (Defaults to 1521): 
sid (site id): dbs3
using connection string: jdbc:oracle:thin:@dbs3.cs.umb.edu:1521:dbs3
Connecting to the database...using connection string: jdbc:oracle:thin:@dbs3.cs.umb.edu:1521:dbs3
Connecting to the database...connected.
pavithra@topcat:~/cs630/hw4$ sqlplus pavithra/pavithra@//dbs3.cs.umb.edu/dbs3

SQL*Plus: Release 12.1.0.2.0 Production on Mon Nov 28 20:57:31 2016

Copyright (c) 1982, 2014, Oracle.  All rights reserved.

Last Successful login time: Mon Nov 28 2016 20:56:45 -05:00

Connected to:
Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
With the Partitioning, OLAP, Advanced Analytics and Real Application Testing options

SQL> select * from flight_assignments order by flno;

      FLNO	  AID	     EID
---------- ---------- ----------
	 2	    9  355548984
	13	   14  552455318
	33	   13  390487451
	68	    4  567354612
	76	    2  141582651
	99	   13  142519864
       304	    5  556784565
       346	    2  242518965
       387	    2	11564812
       702	    5  159542516
      2223	    6	90873519

      FLNO	  AID	     EID
---------- ---------- ----------
      4884	   10  274878974
      5694	    6  356187925
      7789	    7  269734834

14 rows selected.

SQL> select * from delayed_flights;

      FLNO
----------
       701
       149
	34
	 7

SQL> exit
Disconnected from Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
With the Partitioning, OLAP, Advanced Analytics and Real Application Testing options
pavithra@topcat:~/cs630/hw4$ exit
exit

Script done on Mon 28 Nov 2016 08:57:48 PM EST
